
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhruv
 */
public class Moviedetail extends javax.swing.JFrame {

    /**
     * Creates new form NewJFram
     */
    public Moviedetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(8390, 537));
        setMinimumSize(new java.awt.Dimension(839, 537));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Enter room no:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 160, 170, 24);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Type of seat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 290, 100, 24);

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(300, 240, 100, 30);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INSERT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 190, 110, 33);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("No of ticket");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 240, 90, 24);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Movie selected");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 200, 120, 24);

        jLabel4.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(67, 337, 0, 0);

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 150, 270, 30);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Payment");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 400, 110, 24);

        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bahubali", "thor ", "avengers", " " }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(300, 200, 100, 30);

        jRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jRadioButton1.setText("box");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(310, 290, 60, 33);

        jRadioButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jRadioButton2.setText("Balcony");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(310, 330, 100, 33);

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextField3.setText(" ");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(360, 400, 180, 30);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jRadioButton3.setText(" 12 noon to 3 pm");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(420, 230, 159, 33);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jRadioButton4.setText("4 pm to 7 pm");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(420, 260, 160, 33);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jRadioButton5.setText("9 pm to 12 am");
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(420, 290, 160, 33);

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Movie Timing");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 190, 150, 30);

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 240, 110, 30);

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 290, 110, 33);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("MAIN MENU");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(650, 450, 140, 50);

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel10.setText("Next");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 430, 36, 24);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/96184138db47eeac08f6eaa8e7b990f7.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 840, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String movie ,timing = null,seat = null;
   int not,cost = 0,rno;
       rno=Integer.parseInt(jTextField1.getText());
       not=Integer.parseInt(jTextField2.getText());
  movie=(String)jComboBox1.getSelectedItem();
 if(jRadioButton3.isSelected()){
 timing="12noon to 3pm";
 }
         if(jRadioButton4.isSelected()){
 timing="4pm to 7pm";
 }
         if(jRadioButton5.isSelected()){
 timing="9pm to 12am";
 
         }
         if(jRadioButton1.isSelected()){
 seat="box";
         cost=250*not;}
      if(jRadioButton2.isSelected()){
 seat="balcony";
         cost=150*not;}
    
   jTextField3.setText(""+cost); 
   try{
       Class.forName("java.sql.Driver");
       Connection con= DriverManager.getConnection("jdbc:mysql://localhost/dhruv","root","bsms");
        Statement stmt= con.createStatement();
           
       String query= "insert into movie values("+rno+",'"+movie+"',"+not+",'"+timing+"',"+cost+",'"+seat+"');";
       stmt.executeUpdate(query);
      JOptionPane.showMessageDialog(null,"Record is inserted");
       stmt.close();
       con.close();
       
       
       }catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     jTextField1.setText(" ");
        jTextField2.setText(" ");
         jTextField3.setText(" ");
         
             jRadioButton1.setSelected(false);
       jRadioButton2.setSelected(false);
     jRadioButton3.setSelected(false);
       jRadioButton4.setSelected(false);
     
       jRadioButton5.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Task ca=new Task();
      ca.setVisible(true);
      dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       String movie ,timing = null,seat = null;
   int not,cost = 0,rno;
       rno=Integer.parseInt(jTextField1.getText());
       not=Integer.parseInt(jTextField2.getText());
  movie=(String)jComboBox1.getSelectedItem();
 if(jRadioButton3.isSelected()){
 timing="12noon to 3pm";
 }
         if(jRadioButton4.isSelected()){
 timing="4pm to 7pm";
 }
         if(jRadioButton5.isSelected()){
 timing="9pm to 12am";
 
         }
         if(jRadioButton1.isSelected()){
 seat="box";
         cost=250*not;}
      if(jRadioButton2.isSelected()){
 seat="balcony";
         cost=150*not;}
    
   jTextField3.setText(""+cost); 
   try{
       Class.forName("java.sql.Driver");
       Connection con= DriverManager.getConnection("jdbc:mysql://localhost/dhruv","root","bsms");
        Statement stmt= con.createStatement();
           
       String query= "update movie set movie='"+movie+"',noti="+not+",timing='"+timing+"',cost="+cost+",seat='"+seat+"' where room_no="+rno+";";
       stmt.executeUpdate(query);
      JOptionPane.showMessageDialog(null,"Record is updated");
       stmt.close();
       con.close();
       
       
       }catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Food ca=new Food();
        ca.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed

    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moviedetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moviedetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moviedetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moviedetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moviedetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
